/*
 * This source file was generated by the Gradle 'init' task
 */
package jreader;

import java.util.Properties;

import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.pipeline.Annotation;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;

public class App {
    public static void main(String[] args) {
        // Set up Stanford CoreNLP with desired annotators
        Properties props = new Properties();
        props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,entitymentions,depparse,coref,quote");

        // Build the pipeline
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

        // Input text
        String text = "Jack walked over and said to Smith. \"Good Day?\" \"Yes it is.\"";

        // Create an annotation object
        Annotation document = new Annotation(text);

        // Run NLP processing
        pipeline.annotate(document);

        System.out.println(document.get(CoreAnnotations.QuotationsAnnotation.class));
    }
}
