 /*
 * This source file was generated by the Gradle 'init' task
 */
package jreader;

import java.util.concurrent.ExecutionException;

public class App {
    public static void main(String[] args) throws InterruptedException, ExecutionException {
        Narrator narrator = new Narrator();

        //BookReader bookReader = new BookReader();
        //bookReader.readBook();

        String text1 =  "First up is Mr Phelps's store. It's dying, the store is, like the rest of the town and Mr Phelps "+
                        "spends all his time despairing. Even when yer buying stuff from him and he's polite as can be, the"+
                        "despair of him seeps at you like pus from a cut. Ending, says his Noise, Ending, it's all ending and"+
                        "Rags and rags and rags and My Julie, my dear, dear Julie who was his wife and who don't wear"+
                        "no clothes at all in Mr Phelps's Noise."+
                        "\"Hiya, Todd,\" he calls as Manchee and I hurry by."+
                        "\"Hiya, Mr Phelps.\""+
                        "\"Beautiful day, ain't she?\""+
                        "\"She sure is that, Mr Phelps.\""+
                        "\"Beaut!\" barks Manchee and Mr Phelps laughs but his Noise just keeps saying Ending and Julie"+
                        "and rags and pictures of what he misses about his wife and what she used to do as if it's sposed to be"+
                        "unique or something.";

        /*
        + "As they chatted, a waiter approached them. \"Would you like to order anything else?\" he inquired. "
        + "John shook his head. \"No, just the check, please.\" "
        
        + "Emily glanced at her phone. \"I should get going soon. He's expecting me at the office,\" she said."
        + "\"Who's expecting you?\" John asked, raising an eyebrow."
        + "\"Oh, my manager, Mr. Thompson,\" she clarified. \"He wanted an update on the project.\"";
        */
    
        String text2 = "The waiter returned with the bill. \"Take your time,\" he said before walking away. "
        + "John looked at Emily and he said \"Well, let's catch up again soon.\" "
        + "\"Definitely,\" Emily said with a smile."; 

        narrator.narrateText(text1);
        narrator.narrateText(text2);
        
        

        System.exit(0);
    }
}
